#! /bin/bash

readonly _default_cpp_file="main.cpp"

[[ -z "${1}" ]] && _file="${_default_cpp_file}" || _file="${1}"

function _write_to_file
{
    if [[ -s "${_file}" ]]
    then
	echo "Error: File is not empty!"
    else
    	echo -e "${1}" > "${_file}"
    fi
}

_write_to_file \
"#include <iostream>\n\n\
int main()\n\
{\n\
    \n\
    return 0;\n\
}"

exit $RETURN_SUCCESS
